stateDiagram-v2
  %% direction LR

  state CLIMBING_GROUP {
      PREP_CLIMB
      CLIMBING
  }

  state PREPPING_CORAL_GROUP {
      PREP_CORAL_L1
      PREP_CORAL_L2
      PREP_CORAL_L3
      PREP_CORAL_L4
      PREP_CORAL_ZERO
  }
  state PREPPING_CORAL_WITH_ALGAE_GROUP {
      PREP_CORAL_WITH_ALGAE_L1
      PREP_CORAL_WITH_ALGAE_L2
      PREP_CORAL_WITH_ALGAE_L3
      PREP_CORAL_WITH_ALGAE_L4
      PREP_CORAL_ZERO_WITH_ALGAE
  }
  state PREPPING_ALGAE_GROUP {
      PREP_ALGAE_NET
      PREP_ALGAE_PROCESSOR
      PREP_ALGAE_ZERO
  }
  state PREPPING_ALGAE_WITH_CORAL_GROUP {
      PREP_ALGAE_NET_WITH_CORAL
      PREP_ALGAE_PROCESSOR_WITH_CORAL
      PREP_ALGAE_ZERO_WITH_CORAL
  }

  state INTAKE_CORAL_GROUP {
      INTAKE_CORAL_GROUND
      INTAKE_CORAL_STATION
  }

  state INTAKE_ALGAE_GROUP {
      INTAKE_ALGAE_GROUND
      CLEAN_HIGH
      CLEAN_LOW
  }

  state INTAKE_CORAL_WITH_ALGAE_GROUP {
      INTAKE_CORAL_WITH_ALGAE_GROUND
      INTAKE_CORAL_WITH_ALGAE_STATION
  }
  
  state INTAKE_ALGAE_WITH_CORAL_GROUP {
      INTAKE_ALGAE_WITH_CORAL_GROUND
      INTAKE_ALGAE_WITH_CORAL_STATION
      CLEAN_HIGH_WITH_CORAL
      CLEAN_LOW_WITH_CORAL
  }

  HAS_CORAL
  HAS_ALGAE
  HAS_CORAL_AND_ALGAE
  SCORING_CORAL
  SCORING_CORAL_WITH_ALGAE
  SCORING_ALGAE
  SCORING_ALGAE_WITH_CORAL
 
  %% [*] - REPRESENTS NONE (starting and end)
  [*] --> INTAKE_CORAL_GROUP
  [*] --> INTAKE_ALGAE_GROUP
  [*] --> PREP_CLIMB
  %% INTAKING
  INTAKE_CORAL_GROUP --> HAS_CORAL
  INTAKE_ALGAE_GROUP --> HAS_ALGAE
  INTAKE_CORAL_WITH_ALGAE_GROUP --> HAS_CORAL_AND_ALGAE
  INTAKE_ALGAE_WITH_CORAL_GROUP --> HAS_CORAL_AND_ALGAE
  %% HAS SCORING ELEMENT
  HAS_CORAL --> PREPPING_CORAL_GROUP
  HAS_CORAL --> INTAKE_ALGAE_WITH_CORAL_GROUP
  HAS_ALGAE --> INTAKE_CORAL_WITH_ALGAE_GROUP
  HAS_ALGAE --> PREPPING_ALGAE_GROUP
  HAS_CORAL_AND_ALGAE --> PREPPING_CORAL_WITH_ALGAE_GROUP
  HAS_CORAL_AND_ALGAE --> PREPPING_ALGAE_WITH_CORAL_GROUP
  %% PREPPING
  PREPPING_CORAL_GROUP --> SCORING_CORAL
  PREPPING_CORAL_WITH_ALGAE_GROUP --> SCORING_CORAL_WITH_ALGAE
  PREPPING_ALGAE_GROUP --> SCORING_ALGAE
  PREPPING_ALGAE_WITH_CORAL_GROUP --> SCORING_ALGAE_WITH_CORAL
  %% CLIMBING
  PREP_CLIMB --> CLIMBING
  %% SCORING
  SCORING_CORAL --> [*]
  SCORING_ALGAE --> [*]
  SCORING_CORAL_WITH_ALGAE --> HAS_ALGAE
  SCORING_ALGAE_WITH_CORAL --> HAS_CORAL